::Const.Strings.PerkDescription.LegendSmashingShields = "\'If you can\'t get around it, try smashing through. It works!\'.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Abilities targeting Shields do [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color] more damage.\n• If a Shield is destroyed using the \'Split Shield\' skill, [color=" + ::Const.UI.Color.PositiveValue + "]4[/color] Action Points and [color=" + ::Const.UI.Color.PositiveValue + "]50%[/color] of the Fatigue cost are immediately regained.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSmashingShields].Tooltip = ::Const.Strings.PerkDescription.LegendSmashingShields;

::Const.Strings.PerkDescription.LegendSmackdown = "Use your size and strength to bully your way into a prime position.\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Costs 2 AP and builds 10 Fatigue.\n• Prepare to knock back and delay the opponent's turn order to last on your next attack.\n• Reduce their AP by [color=" + ::Const.UI.Color.NegativeValue + "]2[/color] if they are staggered.\n• AP cost is reduced to [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] if wielding Two-Handed Melee weapons.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSmackdown].Tooltip = ::Const.Strings.PerkDescription.LegendSmackdown;

::Const.Strings.PerkDescription.LegendSpecStaffStun = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Staff[/color]\nMaster the movements required to spin your staff in a great flourish that lands with additional force.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Any strike with a staff that would normally daze, also stuns and staggers. This does not apply to AoE attacks.\n• Staff Sweep now applies Dazed.\n• Whack a\' Smack gains [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] chance to hit.",
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecStaffStun].Tooltip = ::Const.Strings.PerkDescription.LegendSpecStaffStun;

::Const.Strings.PerkDescription.LegendTumble = "Make use of your acrobatic skill to improve your movements.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Halves the Fatigue Cost of Lunge, Unarmed Lunge, Footwork, Leap, Sprint, Evasion, Audacious Charge. The Action Point cost of all these skills, except Lunge, is reduced by [color=" + ::Const.UI.Color.PositiveValue + "]1[/color] and that of Leap is halved.\n• This is an upgraded version of 'Furinkazan' and is not stackable.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendTumble].Tooltip = ::Const.Strings.PerkDescription.LegendTumble;

::Const.Strings.PerkDescription.LastStand = "\'This is the hill that you will NOT die on!\'\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+1[/color] additional Melee and Ranged Defense for every [color=" + ::Const.UI.Color.NegativeValue + "]2%[/color] of missing Hitpoints below [color=" + ::Const.UI.Color.NegativeValue + "]66%[/color], and [color=" + ::Const.UI.Color.PositiveValue + "]+1[/color] additional Action Point for every [color=" + ::Const.UI.Color.NegativeValue + "]20%[/color].\n• When below [color=" + ::Const.UI.Color.NegativeValue + "]44%[/color] health this character becomes immune to the effects of subsequent injuries, and is not upset by health losses."
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LastStand].Tooltip = ::Const.Strings.PerkDescription.LastStand;

::Const.Strings.PerkDescription.Indomitable = "\'Mountains cannot be moved, nor taken down!\'\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Costs 5 AP and builds 25 Fatigue.\n• Grants a [color=" + ::Const.UI.Color.PositiveValue + "]50%[/color] damage reduction and immunity to being stunned, knocked back, grabbed, swallowed or culled for one turn.\n• Base Resolve is doubled until the effect ends.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Indomitable].Tooltip = ::Const.Strings.PerkDescription.Indomitable;

::Const.Strings.PerkDescription.QuickHands = "Looking for this?\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Swapping any item in battle a free action with no Action Point cost once every turn.\n• Does not work when swapping a Shield.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.QuickHands].Tooltip = ::Const.Strings.PerkDescription.QuickHands;

::Const.Strings.PerkDescription.LegendMuscularity = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Melee or Throwing Weapon Attack[/color]\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain additional Minimum and Maximum Damage based on your current Hitpoints. The bonus is [color=" + ::Const.UI.Color.PositiveValue + "]1.5%[/color] of your current Hitpoints per AP for attacks with a base Action Point cost of 5 or less and [color=" + ::Const.UI.Color.PositiveValue + "]2%[/color] per AP for attacks with a base Action Point cost of 6 or more.\n• The factor is reduced to [color=" + ::Const.UI.Color.NegativeValue + "]60%[/color] for weapons that have a range of more than one tile and [color=" + ::Const.UI.Color.NegativeValue + "]80%[/color] for most goblin weapons.\n• The bonus damage cannot be higher than [color=" + ::Const.UI.Color.PositiveValue + "]50[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendMuscularity].Tooltip = ::Const.Strings.PerkDescription.LegendMuscularity;

::Const.Strings.PerkDescription.Overwhelm = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Melee Attack[/color]\n\nLearn to take advantage of your high Initiative and prevent the enemy from attacking effectively by overwhelming them with your attacks!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• With every attack, hit or miss, against an opponent that acts after you in the current round, inflict the \'Overwhelmed\' status effect which lowers both Melee Skill and Ranged Skill by [color=" + ::Const.UI.Color.NegativeValue + "]-10%[/color] for one turn.\n• The effect stacks with each attack, up to a maximum of 7 times, and can be applied to multiple targets at once with a single attack.\n• Unlocks an active skill to apply Overwhelmed over a large area, which can be used every other turn.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Overwhelm].Tooltip = ::Const.Strings.PerkDescription.Overwhelm;

::Const.Strings.PerkDescription.LegendBattleheart = "Wade into the thick of battle, dodging blades from behind and above, aware of all around you at the heart of the battle.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Being surrounded no longer affects this character\'s defences at all. Upgraded version of Underdog, immune to Backstabber. Also prevents moral triggers upon enemies entering your Zone of Control";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendBattleheart].Tooltip = ::Const.Strings.PerkDescription.LegendBattleheart;

::Const.Strings.PerkDescription.Underdog = "I\'m used to it.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• The defense malus due to being surrounded by opponents is reduced by [color=" + ::Const.UI.Color.PositiveValue + "]5[/color]. If an attacker has the Backstabber perk, the effect of that perk is negated, and the normal defense malus due to being surrounded is applied instead.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Underdog].Tooltip = ::Const.Strings.PerkDescription.Underdog;

::Const.Strings.PerkDescription.SunderingStrikes = "Learn how to strike best at your targets\' armour to destroy it as fast as possible.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Effectiveness against armour is increased by [color=" + ::Const.UI.Color.PositiveValue + "]20%[/color] of your weapon\'s armour effectiveness.\n• The bonus is increased to [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] for Two-Handed Weapon skills or with a base Action Point cost of 5 or less, and [color=" + ::Const.UI.Color.PositiveValue + "]30%[/color] for Two-Handed Weapon skills with a base Action Point cost of 6 or more. \n• When unarmed, effectiveness against armour is increased by [color=" + ::Const.UI.Color.PositiveValue + "]20%[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.SunderingStrikes].Tooltip = ::Const.Strings.PerkDescription.SunderingStrikes;

::Const.Strings.PerkName.LegendFullForce = "Immovable Object";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFullForce].Name = ::Const.Strings.PerkName.LegendFullForce;	
::Const.Strings.PerkDescription.LegendFullForce = "Put your full weight into defending every blow and gain [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] of the combined Fatigue modifier from body, head, main hand and off hand as additional Damage.\n• You will gain a weakened \'Steadfast\' effect if the combined Fatigue modifier from body, head and off hand is [color=" + ::Const.UI.Color.PositiveValue + "]50[/color] or more.\n• This effect upgrades to the standard \'Steadfast\' once combined Fatigue is at [color=" + ::Const.UI.Color.PositiveValue + "]65[/color] or more.\n• Grants an additional immunity to being Stunned once the combined Fatigue modifier is at [color=" + ::Const.UI.Color.PositiveValue + "]80[/color] or more, this stacks with the \'Steadfast\' effect.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFullForce].Tooltip = ::Const.Strings.PerkDescription.LegendFullForce;

::Const.Strings.PerkName.Slaughterer = "Slaughterer";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Slaughterer].Name = ::Const.Strings.PerkName.Slaughterer;
::Const.Strings.PerkDescription.Slaughterer = "A gruesome display, enemies are more likely to suffer from hits to morale as their allies get carved up and split in two. Melee kills always are fatalities and have a [color=" + ::Const.UI.Color.NegativeValue + "]-15[/color] penalty to enemy Resolve checks.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Slaughterer].Tooltip = ::Const.Strings.PerkDescription.Slaughterer;	
	
::Const.Strings.PerkDescription.LegendCheerOn = "[color=" + this.Const.UI.Color.NegativeValue + "][u]Requires:[/u] Instrument or Banner[/color]\nUse your way with song to cheer on an ally. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+2[/color] Action Points to an adjacent ally. Costs 3 Action Points to perform.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendCheerOn].Tooltip = ::Const.Strings.PerkDescription.LegendCheerOn;

::Const.Strings.PerkDescription.LegendFavouredEnemyGhoul = "Studying these monstrosities has given you insights into the strengths and weaknesses of the pallid necrophilic flesh devourers. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting nachzehrers. Bonus increases the more Nachzehrer you kill.  The bonus depends on how powerful the Nachzehrer is, between [color=" + ::Const.UI.Color.PositiveValue + "]+1%[/color] per Nachzherer, and [color=" + ::Const.UI.Color.PositiveValue + "]+1.5%[/color] per Skin Ghoul you kill. Taking this perk unlocks an extremely difficult legendary contract to hunt elite nachzehrers, also known as Skin Ghouls.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyGhoul].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyGhoul;

::Const.Strings.PerkDescription.LegendFavouredEnemyAlps = "Preparing for the nightmare creepers gives you techniques against their haggard curses.  Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and Resolve while fighting alps. Bonus increases the more Alps you kill, at a rate of [color=" + ::Const.UI.Color.PositiveValue + "]+0.35%[/color] per Alp you kill. Taking this perk unlocks an extremely difficult legendary contract to hunt a fire breathing nightmare demon.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyAlps].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyAlps;	

::Const.Strings.PerkDescription.LegendFavouredEnemyHexen = "Understanding the techniques of the malevolent crones gives you protection against their coven.  Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and Resolve while fighting hexe. Bonus increases the more Hexe you kill at a rate of [color=" + ::Const.UI.Color.PositiveValue + "]+0.5%[/color] per Hexe you kill. Taking this perk unlocks a difficult legendary contract to hunt a coven leader.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyHexen].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyHexen;

::Const.Strings.PerkDescription.LegendFavouredEnemyUnhold = "These gigantic ravenous creatures are dangerous but stupid, that can be used to your advantage. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting unholds. Bonus increases the more Unholds you kill at a rate of [color=" + ::Const.UI.Color.PositiveValue + "]+0.5%[/color] damage per unhold killed. Taking this perk unlocks an extremely difficult legendary contract to hunt a stone skinned Mountain Unhold.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyUnhold].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyUnhold;

::Const.Strings.PerkDescription.LegendFavouredEnemyLindwurm = "Understanding the morphology of these noxious serpents opens up weak spots in their scales. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting lindwurms or serpents. Bonus increases the more Lindwurm you kill at a rate of [color=" + ::Const.UI.Color.PositiveValue + "]+0.9%[/color] damage per Lindwurm killed. Taking this perk unlocks an extremely difficult legendary contract to hunt a burrowing Stollwurm.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyLindwurm].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyLindwurm;

::Const.Strings.PerkDescription.LegendFavouredEnemyDirewolf = "The vicious jaws of a direwolf can tear limbs asunder. In the heat of their blood soaked frenzy, they leave themselves open for counter attack. Understanding these weaknesses grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting direwolves or hyenas. Bonus increases the more wolves you kill at a rate of [color=" + ::Const.UI.Color.PositiveValue + "]+0.15%[/color] damage per direwolf. Taking this perk unlocks an extremely difficult legendary contract to hunt the great white wolf.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyDirewolf].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyDirewolf;	

::Const.Strings.PerkDescription.LegendFavouredEnemySpider = "These skittering deadly bugs can be bested by studying the behaviour of arachnids. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting webnechts. Bonus increases the more webnechts you kill at a rate of [color=" + ::Const.UI.Color.PositiveValue + "]+0.12%[/color] per webnecht you kill. Taking this perk unlocks a legendary contract to hunt extremely poisonous Redback Webnecht.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemySpider].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemySpider;

::Const.Strings.PerkDescription.LegendFavouredEnemySchrat = "The strong branches of a living tree are deadly foes, but trees can be felled with the right knowledge. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting schrats or golems. Bonus increases at a rate of [color=" + ::Const.UI.Color.PositiveValue + "]+0.7%[/color] per schrat you kill. Taking this perk unlocks a legendary contract to hunt an endlessly multiplying Heartwood Schrat.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemySchrat].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemySchrat;

::Const.Strings.PerkDescription.LegendFavouredEnemyOrk = "These marauding brutes are a force to be reckoned with, though their fighting style lacks finesse and can be countered with the right techniques. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting orcs.  Also increases spawn rate of orc champions. Bonus increases the more Orcs you kill, the rate depends on how powerful the orc is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.14%[/color] per orc young, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.8%[/color] per Orc Behemoth you kill.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyOrk].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyOrk;

::Const.Strings.PerkDescription.LegendFavouredEnemyGoblin = "Forces may be gathering to take over the world, but ask someone else, I have no interest in anything but goblins. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting goblins. Also increases spawn rate of goblin champions. Bonus increases the more Goblins you kill, the rate depends on how powerful the goblin is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.15%[/color] per goblin fighter, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.35%[/color] per Goblin Overseer you kill.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyGoblin].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyGoblin;	
	
::Const.Strings.PerkDescription.LegendFavouredEnemyVampire = "The terrifying abilities of the Necrosavants and Embalmed are developed over time beyond memory. Their techniques are honed to perfection, but that also makes them predictable. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting Necrosavants and Embalmed. Bonus increases at a rate of [color=" + ::Const.UI.Color.PositiveValue + "]+0.3% to +0.4%[/color] per necrosavant or Embalmed killed.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyVampire].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyVampire;

::Const.Strings.PerkDescription.LegendFavouredEnemySkeleton = "The legions from the ancient empire still harass this world, yet their connection to the world of the living can be severed. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting skeletons. Also increases spawn rate of skeleton champions.  Bonus increases the more Skeletons you kill, the rate depends on how powerful the skeleton is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.14%[/color] per light skeleton, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.4%[/color] per Skeleton Priest you kill.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemySkeleton].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemySkeleton;

::Const.Strings.PerkDescription.LegendFavouredEnemyZombie = "Shambling corpses come wave on wave, rising sleepless from their graves. They lose something crucial in death, and that can be exploited. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting wiedergangers. Also increases spawn rate of fallen heroes. Bonus increases the more Wiederganger you kill, the rate depends on how powerful the wiederganger is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.05%[/color] per weideganger, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.25%[/color] per Fallen Hero.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyZombie].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyZombie;

::Const.Strings.PerkDescription.LegendFavouredEnemyNoble = "Soldiers in glittering armour and colourful pennants, their pride shall be their undoing. No gods, no masters. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage against noble soldiers. Also increases spawn rate of noble champions. Bonus increases the more noble soldiers you kill, the rate depends on how powerful the noble soldier is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.2%[/color] per footman, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.4%[/color] per Knight you kill.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyNoble].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyNoble;	

::Const.Strings.PerkDescription.LegendFavouredEnemyBandit = "Villainous scum, hiding in the dark and stealing from good folk. The bandits must be purged to restore order in the world. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage against bandits. Also increases spawn rate of bandit champions. Bonus increases the more bandits you kill, the rate depends on how powerful the bandit is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.03%[/color] per Bandit Rabble, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.3%[/color] per Bandit Leader you kill. Taking this perk unlocks  contract to wage war on army of bandits.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyBandit].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyBandit;

::Const.Strings.PerkDescription.LegendFavouredEnemyBarbarian = "Savages, naught but savages. Civilization must be brought to those godless brutes. They may be strong, but they lack skill. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting barbarians. Also increases spawn rate of barbarian champions. Bonus increases the more barbarians you kill, the rate depends on how powerful the barbarian is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.15%[/color] per Barbarian Thrall, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.35%[/color] per Barbarian Champion you kill. Taking this perk unlocks  contract to escort dangerous barbarian prisoner.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyBarbarian].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyBarbarian;

::Const.Strings.PerkDescription.LegendFavouredEnemyArcher = "Some may claim to be the greatest shot in the land, but none have outshot you yet. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting archers. Bonus increases the more archers you kill. This includes Master Archers, Bandit Marksmen and poachers, Militia Archers, Arbalesters and Goblin Ambushers. The bonus depends on how powerful the archer is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.08%[/color] per Bandit Poacher, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.4%[/color] per Master Archer you kill. Also reduces the penalty for targets behind cover by 33%.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyArcher].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyArcher;

::Const.Strings.PerkDescription.LegendFavouredEnemySwordmaster = "The path to martial prowess is beset by the fake and the weak. Only one can be the greatest swordsman. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting elite swordsmen. Bonus increases the more swordsmen you kill. This includes Hedgeknights, Knights, Zweihanders, Swordmasters, Bandit Leaders and Sergeants.  The bonus depends on how powerful the swordsman is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.3%[/color] per Bandit Leader, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.4%[/color] per Knight you kill.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemySwordmaster].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemySwordmaster;	

::Const.Strings.PerkDescription.LegendFavouredEnemyMercenary = "Mercenaries are the worst, no cause, no principles, no honour. They seek only coin, so they shall find only death. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting mercenaries. Bonus increases the more mercenaries, wardogs and bountyhunters you kill.  The bonus depends on how powerful the mercenary is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.09%[/color] per Wardog, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.3%[/color] per Mercenary you kill.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyMercenary].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyMercenary;

::Const.Strings.PerkDescription.LegendFavouredEnemyCaravan = "Civilians are weak and powerless. Their pitiful lives are pathetic, they should be grateful to behold true might in their dying moments. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting civilians. Bonus increases the more civilians you kill. Includes Peasants, Caravan Hands, Caravan Guards, Militia, Militia Veterans, Militia Captains and Militia Archers.  The bonus depends on how powerful the civilian is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.04%[/color] per Peasant, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.2%[/color] per Militia Captain you kill.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyCaravan].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyCaravan;

::Const.Strings.PerkDescription.LegendFavouredEnemySoutherner = "The southern city states are horrific, their slavery and conscription are afronts to human dignity. Their power must be overthrown. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while southerners. Bonus increases the more southerners you kill. This includes Gunners, Officers, Engineers, Assassins, Conscripts, and more.  The bonus depends on how powerful the southerner is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.08%[/color] per Conscript, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.4%[/color] per Veteran Manhunter you kill.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemySoutherner].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemySoutherner;

::Const.Strings.PerkDescription.LegendFavouredEnemyNomad = "The southern nomads are uncivilised heathens, without even towns to their name, they must be brought to heel. Grants [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] bonus to melee skill, ranged skill and maximum damage while fighting nomads. Bonus increases the more nomads you kill. This includes Nomadic outlaws, cutthroats, Desert Stalkers, Slaves, Executioners and more.  The bonus depends on how powerful the nomad is, between [color=" + ::Const.UI.Color.PositiveValue + "]+0.08%[/color] per Nomad Cutthroat, and [color=" + ::Const.UI.Color.PositiveValue + "]+0.4%[/color] per Executioner you kill.\n• At the [color=" + ::Const.UI.Color.PositiveValue + "]18th[/color] character level, you gain an additional perk point.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFavouredEnemyNomad].Tooltip = ::Const.Strings.PerkDescription.LegendFavouredEnemyNomad;

::Const.Strings.PerkDescription.LegendMarkTarget = "Mark a target, reducing their ranged defense by [color=" + ::Const.UI.Color.PositiveValue + "]-20[/color] and melee defense by [color=" + ::Const.UI.Color.PositiveValue + "]-10[/color] for 3 turns.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendMarkTarget].Tooltip = ::Const.Strings.PerkDescription.LegendMarkTarget;	

::Const.Strings.PerkDescription.LegendInTheZone = "Use your armour\'s blend of protection and mobility to punish your foes\' mistakes! Gain a stacking buff that boosts your Melee Skill and Melee Damage by [color=" + ::Const.UI.Color.PositiveValue + "]0.5%[/color] up to a maximum of [color=" + ::Const.UI.Color.PositiveValue + "]15%[/color]. You gain [color=" + ::Const.UI.Color.PositiveValue + "]0.5%[/color] when you dodge a Melee attack and lose [color=" + ::Const.UI.Color.PositiveValue + "]1%[/color] when you get hit by any attack.\n\n When engaged in Melee, the Melee Damage bonus is doubled, up to a maximum of [color=" + ::Const.UI.Color.PositiveValue + "]20%[/color], and the Melee Skill bonus is converted into a Melee Defense one instead.\n\nIf your Initiative is higher than twice your combined body and head armour\'s penalty to Maximum Fatigue, you start the battle with stacks equal to your armour\'s weight above 15.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendInTheZone].Tooltip = ::Const.Strings.PerkDescription.LegendInTheZone;

::Const.Strings.PerkDescription.Rebound = "Fatigue regeneration is increased by [color=" + ::Const.UI.Color.PositiveValue + "]+5[/color] per turn while over [color=" + ::Const.UI.Color.PositiveValue + "]75%[/color] Fatigued.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Rebound].Tooltip = ::Const.Strings.PerkDescription.Rebound;	

::Const.Strings.PerkDescription.LegendBlendIn = "Hold yourself in a way that makes you seem more trouble than its worth, lean into trees, place objects between you and an enemy, and hide behind allies. Makes enemies less likely to attack you instead of an ally, also grants [color=" + ::Const.UI.Color.PositiveValue + "]+5[/color] Ranged Defense and [color=" + ::Const.UI.Color.PositiveValue + "]+3[/color] Melee Defense.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendBlendIn].Tooltip = ::Const.Strings.PerkDescription.LegendBlendIn;		
		
::Const.Strings.PerkName.LegendPiercingShot = "Piercing Shot";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendPiercingShot].Name = ::Const.Strings.PerkName.LegendPiercingShot;	
::Const.Strings.PerkDescription.LegendPiercingShot = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Crossbow [/color]\nLaunch a shot so powerful it can hit two targets in a straight line.\n\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Unlock the [color=" + ::Const.UI.Color.NegativeValue + "]Piercing Shot[/color] skill. It is a powerful shot that can pass straight through one enemy to the enemy behind him.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendPiercingShot].Tooltip = ::Const.Strings.PerkDescription.LegendPiercingShot;	

::Const.Strings.PerkDescription.FastAdaption = "Adapt to your opponent\'s moves! \n• Gain an additional stacking [color=" + ::Const.UI.Color.PositiveValue + "]+20%[/color] chance to hit with each attack that misses an opponent. Bonus is reset upon landing a hit.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.FastAdaption].Tooltip = ::Const.Strings.PerkDescription.FastAdaption;

::Const.Strings.PerkDescription.Fearsome = "Make them scatter and flee!\n\nAny attack that inflicts at least 1 point of damage to Hitpoints triggers a morale check for the opponent with a penalty equal to [color=" + ::Const.UI.Color.NegativeValue + "]20%[/color] of your Resolve, as opposed to with no penalty and only if at or above 15 points of damage.\n• A kill [color=" + ::Const.UI.Color.PositiveValue + "]triples[/color] this effect for your next attack, but if you miss the effect will be wasted. \n•[color=" + ::Const.UI.Color.NegativeValue + "]Does not trigger multiple times from the same attacker on the same target from a single attack[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Fearsome].Tooltip = ::Const.Strings.PerkDescription.Fearsome;

::Const.Strings.PerkDescription.Adrenaline = "Unlocks the \'Adrenaline\' skill which puts you first in the turn order for the next round, to have another turn before your enemies do. Feel the adrenaline rushing through your veins!\n• Picking the perk will also add \'Irresistible Impulse\' to your perk map, which grants additional benefits when using \'Adrenaline\'.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Adrenaline].Tooltip = ::Const.Strings.PerkDescription.Adrenaline;

::Const.Strings.PerkDescription.ReachAdvantage = "Learn to use the superior reach of large weapons to keep the enemy from getting close enough to land a good hit.\n\nWhen hitting an enemy, gain [color=" + ::Const.UI.Color.PositiveValue + "]+100%[/color] of your melee skill as melee defense against them until waiting or ending your turn., you then prevent them from approaching your Zone of Control with an attack of opportunity until next turn with a damage reduction of [color=" + ::Const.UI.Color.NegativeValue + "]20%[/color].\n• Invalid while in the 'En Garde' stance.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.ReachAdvantage].Tooltip = ::Const.Strings.PerkDescription.ReachAdvantage;
	
::Const.Strings.PerkDescription.SpecThrowing = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Throwing Weapon[/color]\nMaster throwing weapons to wound or kill the enemy before they even get close.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Skills build up [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n• Gain 25% of your Melee Skill as additional chance to hit at a distance of 3 tiles or less.\n• Throwing Spears now ignores the damage reduction from the Shield Expert perk.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.SpecThrowing].Tooltip = ::Const.Strings.PerkDescription.SpecThrowing;

::Const.Strings.PerkDescription.Footwork <- "Work those feet!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Active:[/u][/color]\n• Costs 3 AP and builds 10 Fatigue.\n• Unlocks the \'Footwork\' skill which allows you to leave a Zone of Control without triggering free attacks by using skillful footwork.\n• The Fatigue Cost of the skill increases by [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] for every 1 point of total penalty to Maximum Fatigue from head and body armour above 15, up to a maximum Fatigue Cost of [color=" + ::Const.UI.Color.NegativeValue + "]20[/color].\n• Picking the perk will also add \'Furinkazan\' to your perk map, which reduces the cost of \'Footwork\'.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Footwork].Tooltip = ::Const.Strings.PerkDescription.Footwork;

::Const.Strings.PerkDescription.Rotation = "Unlocks the \'Rotation\' skill which allows two characters to switch places while ignoring Zone of Control as long as neither character is stunned, rooted or otherwise disabled.\n• Picking the perk will also add \'Furinkazan\' to your perk map, which reduces the cost of \'Rotation\'.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Rotation].Tooltip = ::Const.Strings.PerkDescription.Rotation;

::Const.Strings.PerkDescription.LegendEvasion = "Enables the character to move swiftly and safely through any Zone of Control for the next whole turn without incurring any free attacks.\n• Picking the perk will also add \'Furinkazan\' to your perk map, which reduces the cost of \'Evasion\'.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendEvasion].Tooltip = ::Const.Strings.PerkDescription.LegendEvasion;

::Const.Strings.PerkDescription.LegendUnarmedTraining = "Focusing on technique, form and stances has given you greater control over your unarmed strikes. Increases the damage of your unarmed attacks based on your Hitpoints and Initiative. The damage is Hitpoints plus Initiative divided by three.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendUnarmedTraining].Tooltip = ::Const.Strings.PerkDescription.LegendUnarmedTraining;	

::Const.Strings.PerkDescription.LegendChoke = "Once an opponent is in a weakened state, it may be easier to choke them out than to fight through their armour. Unlocks the Choke ability which becomes available with no weapons equipped. Hit chance determined by your targets Fatigue, 0% if they are fresh and 100% if they are exhausted. If your target is dazed or parried hitchance is increased by +10%.  If they are stunned or netted you gain +15%. If they are grappled or sleeping you gain +20%. Unarmed mastery doubles your chance to hit. These bonuses stack up to 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendChoke].Tooltip = ::Const.Strings.PerkDescription.LegendChoke;		

::Const.Strings.PerkDescription.LegendSpecFists = "Master the martial arts of unarmed combat. Reduces the AP costs of Hand to Hand, Kick and Grapple. Increases armour effectiveness and increases chance to hit for Hand to Hand, adds damage to Kick.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecFists].Tooltip = ::Const.Strings.PerkDescription.LegendSpecFists;		

::Const.Strings.PerkDescription.HoldOut = "Keep it together! Any negative status effect with a finite duration e.g. Bleeding, Stunned, or Charmed have their duration reduced to [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] turn. Status effects that have their effects grow weaker over several turns (e.g. Goblin Poison) are at their weakest state from the start. Also grants a [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] chance to negate negative status effects such as bleeding and raises the chance to survive being struck down when killed from 33% to 66%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.HoldOut].Tooltip = ::Const.Strings.PerkDescription.HoldOut;

::Const.Strings.PerkDescription.LegendBarterGreed = "Lust for gold and self interest can be a double edged sword, an immediate benefit in one place, may come at the expense of others. \n\n[color=#4f1800][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]0.06% of your gear value[/color] as Melee Skill and Ranged Skill\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]0.08% of your gear value[/color] as Resolve.\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]0.04% of your gear value[/color] as Melee Defence and Ranged Defence.\n\nThis bonus will cap at [color=" + ::Const.UI.Color.NegativeValue + "]+20[/color].\n\nYour global Barter is divided by [color=" + ::Const.UI.Color.NegativeValue + "](1 + Brothers with this perk)[/color] at all times.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendBarterGreed].Tooltip = ::Const.Strings.PerkDescription.LegendBarterGreed;

::Const.Strings.PerkDescription.LegendBalance = "Gain increased defense by balancing your armour\'s weight and mobility.\nGain [color=" + ::Const.UI.Color.PositiveValue + "]+5[/color] Melee Defense and [color=" + ::Const.UI.Color.PositiveValue + "]+5[/color] Ranged Defense when wearing head and body armour with a total weight (penalty to Maximum Fatigue) of 15.\nConvert [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] Ranged Defense to Melee Defense for every 2 points of exceed this value, but drops by [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] for every 10 points that your Current Initiative is below twice your armour weight. Gain a third of the Melee Defense bonus as Ranged Defense.\nThe penalty of your accumulated Fatigue to Initiative is also reduced by [color=" + ::Const.UI.Color.PositiveValue + "]30%[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendBalance].Tooltip = ::Const.Strings.PerkDescription.LegendBalance;

::Const.Strings.PerkDescription.Sprint = "\n[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n•Unlocks the \'Sprint\' skill which allows you to quickly cover 4 tiles or 2 tiles in a straight line, does not work across rough terrain or through enemy zones of control.\n• The Fatigue Cost of the skill increases by [color=" + ::Const.UI.Color.NegativeValue + "]1[/color] for every 1 point of total penalty to Maximum Fatigue from head and body armour above 15, up to a maximum Fatigue Cost of [color=" + ::Const.UI.Color.NegativeValue + "]10[/color].\n• Picking the perk will also add \'Furinkazan\' to your perk map, which reduces the cost of \'Sprint\'.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Sprint].Tooltip = ::Const.Strings.PerkDescription.Sprint;

::Const.Strings.PerkDescription.LegendSlaughter = "If it bleeds, we can kill it. An existing injury can open up avenues of attack for the final slaughter.\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Gain [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] damage when attacking a bleeding enemy.\n• This character gains [color=" + ::Const.UI.Color.PositiveValue + "]+2[/color] Resolve and Initiative for every bleeding character on the field.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSlaughter].Tooltip = ::Const.Strings.PerkDescription.LegendSlaughter;

::Const.Strings.PerkDescription.LegendLithe = "Specialize in Medium Armour! Not as nimble as some but more lithe than others!\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Damage to Hitpoints and armour are reduced by [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] when the total penalty to Maximum Fatigue from head and body armour is between [color=" + ::Const.UI.Color.NegativeValue + "]25[/color] and [color=" + ::Const.UI.Color.NegativeValue + "]35[/color]. Outside this range, the bonus drops exponentially.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendLithe].Tooltip = ::Const.Strings.PerkDescription.LegendLithe;

::Const.Strings.PerkDescription.Nimble = "Specialize in Light Armour! By nimbly dodging or deflecting blows, convert any hits to glancing hits.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Damage to Hitpoints is reduced by between [color=" + ::Const.UI.Color.PositiveValue + "]40%[/color] and [color=" + ::Const.UI.Color.PositiveValue + "]60%[/color] and that to armour by [color=" + ::Const.UI.Color.PositiveValue + "]half[/color] this value.\n• The bonus drops exponentially when wearing head and body armour with a total penalty to Maximum Fatigue above 15. The lighter your armour and helmet, the more you benefit.\n• Brawny does not affect this perk.\n• Does not affect damage from mental attacks or status effects, but can help to avoid receiving them.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Nimble].Tooltip = ::Const.Strings.PerkDescription.Nimble;

::Const.Strings.PerkDescription.SpecThrowing = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Throwing Weapon[/color]\nMaster throwing weapons to wound or kill the enemy before they even get close.\n\n[color=" + ::Const.UI.Color.Passive + "][u]Passive:[/u][/color]\n• Skills build up [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n• Gain 15% of your Ranged Skill as additional armour penetration and 15% of your Melee Skill as additional armour effectiveness when attacking at a distance of 3 tiles or less.\n• Throwing Spear now ignores the damage reduction from the  Shield Expert perk.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.SpecThrowing].Tooltip = ::Const.Strings.PerkDescription.SpecThrowing;

::Const.Strings.PerkDescription.SpecFlail = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Flail[/color]\nMaster flails and circumvent your opponent\'s Shield. Skills build up [color=" + ::Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nLash and Hail ignore the defense bonus of Shields.\n\nPound ignores an additional [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] of armour on head hits.\n\nThresh gains [color=" + ::Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.SpecFlail].Tooltip = ::Const.Strings.PerkDescription.SpecFlail;

::Const.Strings.PerkDescription.LegendSpecialistButcherDamage = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+6-16[/color] damage while using a Butcher\'s Cleaver. 35% of this skill applies to One Handed Cleavers, except whips. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistButcherDamage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistButcherDamage;

::Const.Strings.PerkDescription.LegendSpecialistButcherSkill = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] melee skill while using a Butcher\'s Cleaver. 25% of this skill applies to One Handed Cleavers, except whips. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistButcherSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistButcherSkill;

::Const.Strings.PerkDescription.LegendSpecialistHammerDamage = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+6-16[/color] damage while using a Blacksmith\'s Hammer. 35% of this skill applies to other One Handed Hammers. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistHammerDamage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistHammerDamage;

::Const.Strings.PerkDescription.LegendSpecialistHammerSkill = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + ::Const.UI.Color.PositiveValue + "]+40%[/color] armour damage while using a Blacksmith\'s Hammer. 25% of this skill applies to other One Handed Hammers. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistHammerSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistHammerSkill;

::Const.Strings.PerkDescription.LegendSpecialistKnifeDamage = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+6-16[/color] damage while using a Knife or Shiv. 35% of this skill applies to other daggers. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistKnifeDamage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistKnifeDamage;

::Const.Strings.PerkDescription.LegendSpecialistKnifeSkill = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + ::Const.UI.Color.PositiveValue + "]+40%[/color] armour penetration while using a Knife or Shiv. 25% of this skill applies to other daggers. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistKnifeSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistKnifeSkill;

::Const.Strings.PerkDescription.LegendSpecialistMilitiaDamage = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+6-16[/color] damage while using a militia spear, ancient spear or wooden spear. Only 35% of this skill applies to other spears. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistMilitiaDamage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistMilitiaDamage;

::Const.Strings.PerkDescription.LegendSpecialistMilitiaSkill = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] melee skill while using a militia spear, ancient spear or wooden spear. Only 25% of this skill applies to other spears. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistMilitiaSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistMilitiaSkill;

::Const.Strings.PerkDescription.LegendSpecialistPickaxeDamage = "Allows this character to mine for minerals while assigned to gathering in camp. Gain [color=" + ::Const.UI.Color.PositiveValue + "]+4-12[/color] damage while using a pickaxe, or [color=" + ::Const.UI.Color.PositiveValue + "]+1-3[/color] damage when wielding 2 handed hammers. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistPickaxeDamage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistPickaxeDamage;

::Const.Strings.PerkDescription.LegendSpecialistPickaxeSkill = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] melee skill while using a pickaxe, or [color=" + ::Const.UI.Color.PositiveValue + "]+3[/color] melee skill while using 2 handed hammers. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistPickaxeSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistPickaxeSkill;

::Const.Strings.PerkDescription.LegendSpecialistPitchforkDamage = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+6-16[/color] damage while using a Pitchfork, Wooden Pitchfork, Hoe, Scythe or Wooden Flail. 35% of this perk applies to other polearms including banners. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistPitchforkDamage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistPitchforkDamage;

::Const.Strings.PerkDescription.LegendSpecialistPitchforkSkill = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + ::Const.UI.Color.PositiveValue + "]+25%[/color] armour damage while using a Pitchfork, Wooden Pitchfork, Hoe, Scythe or Wooden Flail. 25% of this perk applies to other polearms and banners. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistPitchforkSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistPitchforkSkill;

::Const.Strings.PerkDescription.LegendSpecialistShortbowDamage = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+6-16[/color] damage while using a shortbow, wonky bow or boondock bow. Only 35% of this skill applies to other bows. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistShortbowDamage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistShortbowDamage;

::Const.Strings.PerkDescription.LegendSpecialistShortbowSkill = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] ranged skill and 25% armour penetration while using a shortbow, wonky bow or boondock bow. Only 25% of this applies to other bows. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistShortbowSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistShortbowSkill;

::Const.Strings.PerkDescription.LegendSpecialistShovelDamage = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+6-16[/color] damage while using a shovel. 35% of this skill applies to two handed maces. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistShovelDamage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistShovelDamage;

::Const.Strings.PerkDescription.LegendSpecialistShovelSkill = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] melee skill and gain the \'Knock Out\' skill while using a shovel. 25% of this bonus melee skill applies to two handed maces. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistShovelSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistShovelSkill;

::Const.Strings.PerkDescription.LegendSpecialistWoodaxeDamage = "Allows this character to harvest wood while gathering in camp. Gain [color=" + ::Const.UI.Color.PositiveValue + "]+6-16[/color] damage while using a Woodcutter\'s Axe or Saw. Only 35% of this skill applies to other axes. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistWoodaxeDamage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistWoodaxeDamage;

::Const.Strings.PerkDescription.LegendSpecialistWoodaxeSkill = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] melee skill while using a Woodcutter\'s Axe or Saw. Only 25% of this bonus melee skill applies to other axes. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistWoodaxeSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistWoodaxeSkill;

::Const.Strings.PerkDescription.LegendSpecialistSickleDamage = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+6-16[/color] damage while using a Sickle or Notched Blade. Only 25% of this bonus melee skill applies to other swords. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistSickleDamage].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistSickleDamage;

::Const.Strings.PerkDescription.LegendSpecialistSickleSkill = "Gain [color=" + ::Const.UI.Color.PositiveValue + "]+12[/color] melee skill and [color=" + ::Const.UI.Color.PositiveValue + "]+25%[/color] armour piercing while using a Sickle or Notched Blade. 25% of this skill applies to one handed swords. This percentage will grow with your current day, rising by 5% each week until you hit 100%.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendSpecialistSickleSkill].Tooltip = ::Const.Strings.PerkDescription.LegendSpecialistSickleSkill;

::Const.Strings.PerkDescription.Bullseye = "Nailed it! The penalty to hitchance when shooting at a target you have no clear line of fire to is reduced from [color=" + ::Const.UI.Color.NegativeValue + "]75%[/color] to [color=" + ::Const.UI.Color.NegativeValue + "]33%[/color] for ranged weapons.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Bullseye].Tooltip = ::Const.Strings.PerkDescription.Bullseye;

::Const.Strings.PerkDescription.Lookout = "Learn to find your enemies before they find you. Vision is increased by [color=" + ::Const.UI.Color.PositiveValue + "]+1[/color] and the penalty at night is reduced by [color=" + ::Const.UI.Color.PositiveValue + "]50%[/color]. Also grants [color=" + ::Const.UI.Color.PositiveValue + "]+10%[/color] scouting in camp.",
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.Lookout].Tooltip = ::Const.Strings.PerkDescription.Lookout;

::Const.Strings.PerkDescription.LegendNetRepair = "Many years spent repairing and packing nets allows you to create nets and wield them more effectively.\n• Unlocks the Net recipe in the crafting tent. Also grants +10 melee defense while holding a net and reduce AP cost of throwing nets to [color=" + ::Const.UI.Color.PositiveValue + "]3[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendNetRepair].Tooltip = ::Const.Strings.PerkDescription.LegendNetRepair;

::Const.Strings.PerkDescription.LegendNetCasting = "[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Allows you to throw a free makeshift net, it can only be used once per battle.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendNetCasting].Tooltip = ::Const.Strings.PerkDescription.LegendNetCasting;

::Const.Strings.PerkDescription.LegendMasteryNets = "Use advanced net throwing techniques to reduce the Fatigue cost by [color=" + ::Const.UI.Color.PositiveValue + "]25%[/color] and increases the range of all nets to [color=" + ::Const.UI.Color.PositiveValue + "]4[/color] tiles.\n• Makes throwing other tools such as pots more effective.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendMasteryNets].Tooltip = ::Const.Strings.PerkDescription.LegendMasteryNets;

::Const.Strings.PerkDescription.LegendEscapeArtist = "Others see it as magic, but your deft hands know better.\n• Grants a chance to dodge nets with ranged defence.\n• At the start of your turn, perform a free Break Free action.\n• Grants a baseline [color=" + ::Const.UI.Color.PositiveValue + "]99%[/color] chance to break free from rooting effects, such as nets and webs.\n• Reduces the Action Point cost of breaking free yourself and your allies by [color=" + ::Const.UI.Color.PositiveValue + "]2[/color] and the Fatigue cost by [color=" + ::Const.UI.Color.PositiveValue + "]70%[/color].";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendEscapeArtist].Tooltip = ::Const.Strings.PerkDescription.LegendEscapeArtist;

::Const.Strings.PerkDescription.LegendPackleader = "Dogs can instinctively identify a pack leader, knowledge of their habits allows you to become the leader of their pack. Unlocks the ability to store additional dog items in your bags and use them in battle. Grants each dog you unleash the perk Assured Conquest and increases him [color=" + ::Const.UI.Color.PositiveValue + "]100%[/color] armour.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendPackleader].Tooltip = ::Const.Strings.PerkDescription.LegendPackleader;

::Const.Strings.PerkDescription.LegendDogBreeder = "Intimate knowledge of dog care and conditions required for breeding allows you to successfully breed dogs. Unlocks a recipe in the crafting tent for breeding dogs. Grants each dog you unleash the perks Fast Adaption and Backswing, also increases him [color=" + ::Const.UI.Color.PositiveValue + "]5[/color] Melee Skill.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendDogBreeder].Tooltip = ::Const.Strings.PerkDescription.LegendDogBreeder;

::Const.Strings.PerkDescription.LegendDogHandling = "You have mastered the art of training dogs. In the heat of battle your hounds will respond and react to your commands. Order them to attack or defend allies. Grants each dog you unleash the perk Overwhelm, also increases him [color=" + ::Const.UI.Color.PositiveValue + "]5[/color] Melee Defense.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendDogHandling].Tooltip = ::Const.Strings.PerkDescription.LegendDogHandling;

::Const.Strings.PerkDescription.LegendDogWhisperer = "You have a way with dogs, the bond you form with them imbues each dog with more confidence and strength, knowing that you are there gives them strength. Grants each dog you unleash the perks \'Colossus\', \'Fortified Mind\', \'Underdog\' and \'Clarity\'.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendDogWhisperer].Tooltip = ::Const.Strings.PerkDescription.LegendDogWhisperer;

::Const.Strings.PerkDescription.LegendDogMaster = "[color=" + ::Const.UI.Color.Active + "][u]Active:[/u][/color]\n• Costs 4 AP and builds 15 Fatigue.\n• By spending one item of food you can restore a dog's morale within 7 tiles. The food item is chosen at random and the perk does not work if you have less than 25 food. Grants each dog you unleash the perk \'Dodge\'.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendDogMaster].Tooltip = ::Const.Strings.PerkDescription.LegendDogMaster;

::Const.Strings.PerkDescription.LegendFieldTreats = "Make liberal use of alcohol and food to motivate your mercenaries. Spend 20 food to take someone from wavering to steady and reduces current Fatigue by [color=" + ::Const.UI.Color.PositiveValue + "]-15%[/color], cannot be applied to someone who has already been treated before.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFieldTreats].Tooltip = ::Const.Strings.PerkDescription.LegendFieldTreats;

::Const.Strings.PerkDescription.LegendFieldTriage = "Spend medicine to heal a unit on the battlefield, at a rate of 1 medicine for every 2 health. Heals an additional [color=" + ::Const.UI.Color.PositiveValue + "]20[/color] Hitpoints per usage of bandages on allies.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendFieldTriage].Tooltip = ::Const.Strings.PerkDescription.LegendFieldTriage;

::Const.Strings.PerkDescription.LegendDrumsOfWar = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Instrument[/color]\nLearn powerful rhythms that drive your allies on. Unlocks the Drums of War skill that restores [color=" + ::Const.UI.Color.PositiveValue + "]+4[/color] Fatigue to every ally within eight tiles.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendDrumsOfWar].Tooltip = ::Const.Strings.PerkDescription.LegendDrumsOfWar;

::Const.Strings.PerkDescription.LegendDrumsOfLife = "[color=" + ::Const.UI.Color.NegativeValue + "][u]Requires:[/u] Instrument or Unarmed[/color]\nLearn powerful rhythms that drive your allies on. Unlocks the Drums of Life skill that restores [color=" + ::Const.UI.Color.PositiveValue + "]+8[/color] health to every ally within eight tiles.";
::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs.LegendDrumsOfLife].Tooltip = ::Const.Strings.PerkDescription.LegendDrumsOfLife;


local poleWeaponStrings = [
	"SpecAxe",
	"SpecHammer",
	"SpecMace",
	"SpecPolearm",
	"SpecSpear"
];

foreach (s in poleWeaponStrings)
{
	::Const.Strings.PerkDescription[s] = ::MSU.String.replace(::Const.Strings.PerkDescription[s], "no longer has a penalty", "has a reduced penalty");
	::Const.Strings.PerkDescription[s] = ::MSU.String.replace(::Const.Strings.PerkDescription[s], "no longer have a penalty", "have a reduced penalty");
	::Const.Perks.PerkDefObjects[::Const.Perks.PerkDefs[s]].Tooltip = ::Const.Strings.PerkDescription[s];
}
